"""third migrate

Revision ID: d61e9d6fcea4
Revises: 909be7b6bac6
Create Date: 2019-09-25 12:24:55.651405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61e9d6fcea4'
down_revision = '909be7b6bac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('feedback', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'feedback')
    # ### end Alembic commands ###
